name: build-upload-prd
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
            mkdir dist
            echo ${{ github.sha }} > dist/release.txt
            echo fuga > dist/fuga.txt
            echo hoge > dist/hoge.txt
            echo foo > dist/foo.txt
      - name: Test
        run: cat dist/release.txt
      - name: Compress
        run: tar -zcf build-assets.tar.gz ./dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-assets.tar.gz
